# Generated by Django 6.0.2 on 2026-03-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
