# Generated by Django 6.0.2 on 2026-03-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_review_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="comment",
        ),
    ]
