# Generated by Django 6.0.2 on 2026-03-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_rename_date_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
