# Generated by Django 6.0.2 on 2026-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Paid", "Pending"),
                    ("Ready To Ship", "Ready To Ship"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Cancled"),
                ],
                default="Not Paid",
                max_length=20,
            ),
        ),
    ]
